### ISSUE TITLE
Are you sure missing file?

### ISSUE THREAD

**Issue by tuanteku9x** [Widiskel/catopia-bot#1]
Are you sure missing file?.
npm run start or node index.js can't run

**Comment by copycatcodex** [comment]
I can run it.
with manually steps like
1. edit config.js manual
2. move folder config inside folder app
3. and run `node app/index.js`

**Comment by copycatcodex** [comment]
![Screenshot 2024-08-27 091447](https://github.com/user-attachments/assets/7a984568-70a7-4bf1-bf2e-c004c98db424)

**Comment by tuanteku9x** [comment]
> ![Screenshot 2024-08-27 091447](https://private-user-images.githubusercontent.com/117299638/361629234-7a984568-70a7-4bf1-bf2e-c004c98db424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjUzNDQsIm5iZiI6MTcyNDcyNTA0NCwicGF0aCI6Ii8xMTcyOTk2MzgvMzYxNjI5MjM0LTdhOTg0NTY4LTcwYTctNGJmMS1iZjJlLWMwMDRjOThkYjQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGM1NzM5Mjk1NDMyMTNkYTQwMTE3ZTQ2NWRhOGY4MzUxZjhkYzY2Yzg5ZGU0NzUwMzg0OGViOWVkNThhZjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-5CVMjA_qJ__jIMBhXOPfv5PoEaJwY5x7f0JESWGCF4)

ok pro

**Comment by Widiskel** [comment]
guess it solved, thanks @copycatcodex
