### ISSUE TITLE
New Error :v

### ISSUE THREAD

**Issue by copycatcodex** [Widiskel/catopia-bot#2]
![image](https://github.com/user-attachments/assets/04ae30e2-b8e9-4335-ad30-48744224e282)
new error after error lowercase ..

**Comment by tuanteku9x** [comment]
Yes; Error : Cannot read properties of undefined (reading 'toLowerCase'), Retrying after 30 Second

**Comment by copycatcodex** [comment]
fixed by author

**Comment by tuanteku9x** [comment]
> fixed by author

where is fixed? I don't see pro

**Comment by Widiskel** [comment]
just pull

**Comment by Widiskel** [comment]
im add new update regarding upgrade pet just in few sec ago, go pull it
